quanser:

    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 100
      ns: /quanser

    junta1_joint_effort_controller:
      type: effort_controllers/JointEffortController
      joint: joint_bloco_link1

    junta2_joint_effort_controller:
      type: effort_controllers/JointEffortController
      joint: joint_link1_link2
