quanser:

    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 100

    joint_bloco_link1_velocity_controller:
      type: effort_controllers/JointVelocityController
      joint: joint_bloco_link1
      pid: {p: 2.1, i: 0.4, d: 0.0}

    joint_link1_link2_velocity_controller:
      type: effort_controllers/JointVelocityController
      joint: joint_link1_link2
      pid: {p: 1.7, i: 0.6, d: 0.0}
